### ISSUE TITLE
Handle scenario where an [IonPropertyName] annotated property name conflicts with a field name in the same class

### ISSUE THREAD

**Issue by justing-bq** [amzn/ion-object-mapper-dotnet#29]
The property should get precedence over the field during serialization and deserialization.

**Comment by amzn-paunort** [comment]
Quoting here from #60,

> This came up in my work on #29, where the ability to log would allow us to report this field naming conflict as a non-fatal warning to the user, instead of either a) silently ignoring the field or b) throwing some sort of name conflict error.

**Comment by guyilin-amazon** [comment]
Per the specification https://github.com/amzn/ion-object-mapper-dotnet/blob/main/SPEC.md#naming, if the property name conflicts with a field name of the same class, the property will get precedence over the field during serialization and/or deserialization, whether the field is ignored or not. We should check if our current implementation is compliant with the spec, i.e. ignore fields when property name conflicts with a field name of the same class.

Add logging would increase the clarity for such "unusual" behaviors, but since we have clarified this in the spec, the logging would be an optional and separate part for this issue.
